@startuml
' Simplified Model Class Diagram focusing on Person entity composition
' Shows how AddressBook contains UniquePersonList and UniqueTagList
' Person entities (Student/Tutor/Parent) have Name, Phone, Email, Address attributes
' Tags allow flexible categorization of persons in the tuition centre
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
